export enum ActionType {
  FETCH_ALL_TODOS = "FETCH_ALL_TODOS",
  CREATE_TODO = "CREATE_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  DELETE_TODO = "DELETE_TODO",
  TOGGLE_TODO = "TOGGLE_TODO",
  SELECT_TODO = "SELECT_TODO",
}
